"""empty message

Revision ID: 702e1b4c7fc4
Revises: 
Create Date: 2019-01-10 11:43:56.207466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702e1b4c7fc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NN_Query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdb_query', sa.String(length=8), nullable=True),
    sa.Column('protein_file', sa.String(), nullable=True),
    sa.Column('query_time', sa.DateTime(), nullable=False),
    sa.Column('user_email', sa.Integer(), nullable=True),
    sa.CheckConstraint(u'NOT(pdb_query IS NULL AND protein_file IS NULL)'),
    sa.ForeignKeyConstraint(['user_email'], ['Users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_NN_Query_query_time'), 'NN_Query', ['query_time'], unique=False)
    op.drop_index('ix_NN__query_timestamp', table_name='NN__query')
    op.drop_table('NN__query')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NN__query',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('query', sa.VARCHAR(length=8), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_NN__query_timestamp', 'NN__query', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_NN_Query_query_time'), table_name='NN_Query')
    op.drop_table('NN_Query')
    # ### end Alembic commands ###
