"""Added email confirmation columns

Revision ID: d79fe1950ddb
Revises: 702e1b4c7fc4
Create Date: 2019-01-10 12:52:00.089684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79fe1950ddb'
down_revision = '702e1b4c7fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('confirmation_link_sent_on', sa.DateTime(), nullable=True))
    op.add_column('Users', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    op.add_column('Users', sa.Column('email_confirmed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'email_confirmed_on')
    op.drop_column('Users', 'email_confirmed')
    op.drop_column('Users', 'confirmation_link_sent_on')
    # ### end Alembic commands ###
